version: 2

project_name: glua

builds:
  - id: glua
    main: ./cmd/glua/
    binary: glua
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: binary
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: package-register
    name: glua
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
